services:
  api-gateway:
    image: traefik:v3.2.3
    ports:
      - "80:80"       # HTTP
      - "9080:8080"
    command:
      # Общая конфигурация Traefik
      - "--log.level=DEBUG"                                     # Логгирование (можно указать DEBUG)
      - "--api.insecure=true"                                  # Админ-панель Traefik (уберите в продакшене)
      - "--providers.docker=true"                              # Подключение к Docker
      - "--providers.docker.exposedbydefault=false"            # Контейнеры не экпонируются по умолчанию
      - "--entrypoints.http.address=:80"                       # Входная точка для HTTP
      - "--serversTransport.insecureSkipVerify=true"
    volumes:
      # Доступ к Docker API
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    #    labels:
    #      # Настройка Dashboard роутера
    #      - "traefik.enable=true"
    #      - "traefik.http.routers.traefik-router.rule=PathPrefix(`/gateway/`)"
    #      - "traefik.http.routers.traefik-router.entrypoints=http"
    #      - "traefik.http.routers.traefik-router.service=api@internal"
    restart: unless-stopped

  smart-service:
    build:
      context: ./dev/
      dockerfile: Dockerfile
    image: hidiv/php-dev:8.3.16-smart-links
    env_file: .env.smart
    extra_hosts:
      ## Чтобы зафиксировать адрес gateway, на котором может слушать phpstorm
      - "host.docker.internal:host-gateway"
    environment:
      ## Фишка для phpstorm
      ## Идем Settings > Languages & Frameworks > PHP и создаем server с именем otus-smart-links
      PHP_IDE_CONFIG: "serverName=otus-smart-links"
    volumes:
      ## Первым монтируем основной каталог
      - type: bind
        source: ../smart-service
        target: /var/www/html
    labels:
      - "traefik.enable=true"
      # Маршрут по префиксу /smart/
      - "traefik.http.routers.smart-router.rule=PathPrefix(`/smart/`)"
      - "traefik.http.routers.smart-router.entrypoints=http"
      # StripPrefix: удаляем /smart перед проксированием
      - "traefik.http.routers.smart-router.middlewares=smart-strip"
      - "traefik.http.routers.smart-router.service=smart-service"
      # Определяем сервисный порт Apache PHP
      - "traefik.http.services.smart-service.loadbalancer.server.port=80"
      # Описание middleware StripPrefix
      - "traefik.http.middlewares.smart-strip.stripprefix.prefixes=/smart"
      - "traefik.http.middlewares.smart-strip.stripprefix.forceslash=true"
    restart: unless-stopped
    depends_on:
      - api-gateway
      - smart-db

  smart-db:
    image: mariadb:10.11.10-ubi9
    ports:
      ## Порты наружу можно не пробрасывать, если нет потребности коннектиться напрямую к БД
      - "3306:3306"
    volumes:
      - type: volume
        source: smart-db-data
        target: /var/lib/mysql
    command: --max_allowed_packet=32505856 # Set max_allowed_packet to 256M (or any other value)
    environment:
      ## Пароль root
      MARIADB_ROOT_PASSWORD: "${SMART_DB_ROOT_PASSWORD}"
      ## Схема БД
      MARIADB_DATABASE: "${SMART_DB_DATABASE}"
      ## Логин для доступа
      MARIADB_USER: "${SMART_DB_USER}"
      ## Пароль для доступа
      MARIADB_PASSWORD: "${SMART_DB_PASS}"
    restart: unless-stopped

volumes:
  smart-db-data:
